const AUTH_NAGINATIONS = {
  LOGIN: 'LOGIN',
  REGISTER: 'REGISTER',
  FORGOT_PASSWORD: 'FORGOT_PASSWORD',
  RESET_PASSWORD: 'RESET_PASSWORD'
};

const TAB_NAVIGATIONS = {
  PRODUCTS: 'PRODUCTS',
  CART: 'CART',
  PROFILE: 'PROFILE'
};

export { AUTH_NAGINATIONS, TAB_NAVIGATIONS };
