const AUTH_NAGINATIONS = {
  LOGIN: 'LOGIN',
  REGISTER: 'REGISTER',
  FORGOT_PASSWORD: 'FORGOT_PASSWORD',
  RESET_PASSWORD: 'RESET_PASSWORD'
};

const TAB_NAVIGATIONS = {
  NAME: 'TAB_NAVIGATIONS',
  PRODUCTS: 'PRODUCTS',
  CART: 'CART',
  PROFILE: 'PROFILE',
  SINGLE_PRODUCT: 'SINGLE_PRODUCT',
  CHECKOUT: 'CHECKOUT'
};

export { AUTH_NAGINATIONS, TAB_NAVIGATIONS };
